brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
brokerIP1=broker
listenPort=10911
autoCreateTopicEnable=false
flushDiskType=SYNC_FLUSH
brokerRole=ASYNC_MASTER
mappedFileSizeCommitLog=67108864
storePathRootDir=/home/rocketmq/store
